// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "jwt": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hirokisan/go-sandbox/go-api/design/jwt
// --out=$(GOPATH)/src/github.com/hirokisan/go-sandbox/go-api/jwt
// --version=v1.3.1

package app
