// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "jwt": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/hirokisan/go-sandbox/go-api/design/jwt
// --out=$(GOPATH)/src/github.com/hirokisan/go-sandbox/go-api/jwt
// --version=v1.3.1

package app

// The common media type to all request responses for this example (default view)
//
// Identifier: application/vnd.goa.examples.security.success; view=default
type Success struct {
	// Always true
	OK bool `form:"ok" json:"ok" yaml:"ok" xml:"ok"`
}
