version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:3.4.19-jessie
    ports:
      - "27017:27017"

  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11211:11211"
