// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "sample": sample Resource Client
//
// Command:
// $ goagen
// --design=github.com/hirokisan/go-sandbox/go-api/design/api2
// --out=$(GOPATH)/src/github.com/hirokisan/go-sandbox/go-api/api2
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ShowSamplePath computes a request path to the show action of sample.
func ShowSamplePath(bottleID int) string {
	param0 := strconv.Itoa(bottleID)

	return fmt.Sprintf("/sample/%s", param0)
}

// Get sample by id
func (c *Client) ShowSample(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowSampleRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowSampleRequest create the request corresponding to the show action endpoint of the sample resource.
func (c *Client) NewShowSampleRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
