// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "sample": Application User Types
//
// Command:
// $ goagen
// --design=github.com/hirokisan/go-sandbox/go-api/design/api2
// --out=$(GOPATH)/src/github.com/hirokisan/go-sandbox/go-api/api2
// --version=v1.3.1

package client
