// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/hirokisan/go-sandbox/go-api/design/api1
// --out=$(GOPATH)/src/github.com/hirokisan/go-sandbox/go-api/api1
// --version=v1.3.1

package app
