// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "sample": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hirokisan/go-sandbox/go-api/design/api2
// --out=$(GOPATH)/src/github.com/hirokisan/go-sandbox/go-api/api2
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// SampleHref returns the resource href.
func SampleHref(bottleID interface{}) string {
	parambottleID := strings.TrimLeftFunc(fmt.Sprintf("%v", bottleID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/sample/%v", parambottleID)
}
