// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "sample": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/hirokisan/go-sandbox/go-api/design/design2
// --out=$(GOPATH)/src/github.com/hirokisan/go-sandbox/go-api/api2
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// A sample of wine (default view)
//
// Identifier: application/vnd.goa.example.sample+json; view=default
type GoaExampleSample struct {
	// API href for making requests on the sample
	Href string `form:"href" json:"href" yaml:"href" xml:"href"`
	// Unique sample ID
	ID int `form:"id" json:"id" yaml:"id" xml:"id"`
	// Name of wine
	Name string `form:"name" json:"name" yaml:"name" xml:"name"`
}

// Validate validates the GoaExampleSample media type instance.
func (mt *GoaExampleSample) Validate() (err error) {

	if mt.Href == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "href"))
	}
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}
