basePath: /api/v1
consumes:
- application/json
definitions:
  Success:
    description: The common media type to all request responses for this example (default
      view)
    example:
      ok: false
    properties:
      ok:
        description: Always true
        example: false
        type: boolean
    required:
    - ok
    title: 'Mediatype identifier: application/vnd.goa.examples.security.success; view=default'
    type: object
host: localhost:8080
info:
  description: jwt
  title: jwt
  version: v1
paths:
  /basic:
    get:
      description: This action is secure with the basic_auth scheme
      operationId: basic#secure
      produces:
      - application/vnd.goa.examples.security.success
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Success'
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - basic_auth: []
      summary: secure basic
      tags:
      - basic
  /basic/unsecure:
    get:
      description: This action does not require auth
      operationId: basic#unsecure
      produces:
      - application/vnd.goa.examples.security.success
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Success'
      schemes:
      - http
      summary: unsecure basic
      tags:
      - basic
  /jwt:
    get:
      description: |-
        This action is secured with the jwt scheme

        Required security scopes:
          * `api:access`
      operationId: jwt#secure
      parameters:
      - description: Force auth failure via JWT validation middleware
        in: query
        name: fail
        required: false
        type: boolean
      produces:
      - application/vnd.goa.examples.security.success
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Success'
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - jwt:
        - api:access
      summary: secure jwt
      tags:
      - jwt
  /jwt/signin:
    post:
      description: Creates a valid JWT
      operationId: jwt#signin
      responses:
        "204":
          description: No Content
          headers:
            Authorization:
              description: Generated JWT
              type: string
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - SigninBasicAuth: []
      summary: signin jwt
      tags:
      - jwt
  /jwt/unsecure:
    get:
      description: This action does not require auth
      operationId: jwt#unsecure
      produces:
      - application/vnd.goa.examples.security.success
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Success'
      schemes:
      - http
      summary: unsecure jwt
      tags:
      - jwt
produces:
- application/json
responses:
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Success'
  Unauthorized:
    description: Unauthorized
schemes:
- http
securityDefinitions:
  SigninBasicAuth:
    type: basic
  basic_auth:
    type: basic
  jwt:
    description: |2-


      **Security Scopes**:
        * `api:access`: API access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
